### ISSUE TITLE
Lots of code in different stores can be consolidated

### ISSUE THREAD

**Issue by discentem** [discentem/cavorite#106]
https://github.com/discentem/cavorite/blob/main/internal/stores/s3.go#L120-L153

and 

https://github.com/discentem/cavorite/blob/main/internal/stores/gcs.go#L69-L92

are identical. Instead maintaining this code in each of the store providers (and future providers), we should abstract this out.

**Comment by discentem** [comment]
@natewalck do you feel that this issue is resolved by #111?

**Comment by natewalck** [comment]
Not entirely.

#111 still does config checking within the store. (Specifically, checking for the metadata extension config to exist)

If a config is required for cavorite to run, we should be checking it and bailing (or set a default). This should live here: https://github.com/discentem/cavorite/blob/main/internal/cli/init.go#L72

The config code owns the config validation, if that makes sense.

**Comment by discentem** [comment]
Closing this. Opened https://github.com/discentem/cavorite/issues/113 to keep track of the config validation changes @natewalck is requesting
